version: "3.8"

services:
  mysql:
    container_name: mysqlDani
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ab1234Ab
      MYSQL_DATABASE: docker
    healthcheck:
      test: "mysql -root -Ab1234Ab platform -e 'select 1'"
      interval: 1s
      retries: 120
    cap_add:
        - SYS_NICE
    networks:
      docker-net:

  springboot-restful-webservices.jar-1.jar:
    container_name: springbootDani
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      docker-net:
    restart: on-failure

networks:
  docker-net:
